version: 0.2

  commands:
    - echo Building...

phases:

  install:
    runtime-versions:
      nodejs: 8

  build:
    commands:
      - echo nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - PeterTountasResume.pdf
    - styles/*
    - images/*